swagger: '2.0'
info:
  version: 1.0.0
  title: Node Service 2
  license:
    name: Proprietary
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
  - https
paths:
##########--SWAGGER--##########
  '/swagger.json':
    get:
      tags:
        - Spec
      operationId: retrieveSpec
      description: |
        Retrieve OpenAPI spec.
      responses:
        '200':
          description: Successful
          schema:
            type: object    
##########--User--###########
  '/user/{email}':
    get:
      description: get User
      operationId: getUser
      tags:
        - Register
      parameters:
        - $ref: '#/parameters/email'
      responses:
        '200':
          description: User is retrieved
          schema:
            type: object
        '400':
          description: Bad Request
          schema:
            type: object
        default:
          description: Unexpected error
          schema:
            type: object

parameters:
  email:
    name: email
    in: path
    required: true
    type: string
        