swagger: '2.0'
info:
  version: 1.0.0
  title: Node Mongo Example
  license:
    name: Proprietary
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
  - https
paths:
##########--GET PEOPLE--##########
  /:
    get:
      tags: 
        - GetRoute
      operationId: getRoute
      responses:
        '200':
          description: Success
          schema:
            type: array
        '400':
          description: Missing Record
          schema:
            type: object
##########--POST PERSON--##########
  /person:
    post:
      tags:
        - PostRoute
      operationId: postRoute
      parameters:
        - in: body
          name: name
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Success
          schema:
            type: object
##########--SWAGGER--##########
  /swagger.json:
    get:
      tags:
        - Spec
      operationId: retrieveSpec
      description: |
        Retrieve OpenAPI spec.
      responses:
        '200':
          description: Successful
          schema:
            type: object 

     
            